repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
    -   id: black
-   repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
    -   id: isort
-   repo: https://github.com/mwouts/jupytext
    rev: v1.16.0
    hooks:
    -   id: jupytext
        args: [
            '--opt', 'notebook_metadata_filter=-kernelspec',
            '--from', 'myst', '--to', 'myst',
            '--pipe', 'black', '--pipe-fmt', 'py:percent'
        ]
        files: 'docs/source/examples/.*\.md'
        additional_dependencies:
        -   black[jupyter]==23.12.1
