# Regular QA workflow (pull requests, main branch)

name: Test

on:
  push:
    branches:
      - main
      - ipynb
  pull_request_target:
    branches:
      - main

jobs:
  code-quality:
    uses: ./.github/workflows/code-quality.yml
  unit-tests:
    uses: ./.github/workflows/unit-tests.yml
    needs: [code-quality]
  notebook-examples:
    uses: ./.github/workflows/notebook-examples.yml
    needs: [unit-tests]

  trigger-rtd-build:
    runs-on: ubuntu-latest
    needs: [notebook-examples, unit-tests, code-quality]
    steps:
      - name: Trigger RTD build for ipynb branch
        env:
          RTD_HOOK_TOKEN: ${{ secrets.RTD_HOOK_TOKEN }}
        run: curl -X POST -d "branches=ipynb" -d "token=$RTD_HOOK_TOKEN" -d "default_branch=main" https://readthedocs.com/api/v2/webhook/gurobi-optimization-gurobipy-pandas/11030/
